### PR TITLE
Added 3 languages

### PR DESCRIPTION
**Pull request by GGGaming71**

### CODE REVIEW

**Comment by froxcey** [comment]
Did you use Google Translate? You seriously understand Japanese, Korean, and Arabic?

**Comment by GGGaming71** [comment]
> Did you use Google Translate? You seriously understand Japanese, Korean, and Arabic?

I Did 😬 but i can assure you the arabic translation is correct idk about Japanese and korean but yes i did use Google translate for the translation

**Comment by GGGaming71** [comment]
But i mean im pretty sure if you re-translate to english it would have an accurate meaning

**Review by froxcey — CHANGES_REQUESTED** [review]
So in the translating guideline, there's regulation regarding the use of tools like translating software. By adding a translation using Google Translate, you should understand the meaning of each sentence and make sure they are correct. People can tell if it's Google translate and it will sound unnatural if you don't review. As much as I want all languages on the website, you might need to remove Korean and Japanese. Thank you tho, I can see that you really want to help and I appreciate it. Re-request review when you're ready.

**Comment by GGGaming71** [comment]
> So in the translating guideline, there's regulation regarding the use of tools like translating software. By adding a translation using Google Translate, you should understand the meaning of each sentence and make sure they are correct. People can tell if it's Google translate and it will sound unnatural if you don't review. As much as I want all languages on the website, you might need to remove Korean and Japanese. Thank you tho, I can see that you really want to help and I appreciate it. Re-request review when you're ready.

so i remove the japanese and korean translations and keep the arabic?

**Comment by froxcey** [comment]
Yes, only translate what you understand

**Comment by GGGaming71** [comment]
> Yes, only translate what you understand

ok but should i translate the social media and Avdan and AvdanOS names??

**Comment by froxcey** [comment]
Translate social media if they are available. Same goes for AvdanOS. Since OS stands for operating system, Chinese translation sometimes can have translation. If translation is not available, leave it blank and nothing will go wrong.

**Comment by GGGaming71** [comment]
okay i think im finished with the translation now

**Review by froxcey — APPROVED** [review]
Tested and LGTM!

vibe

**Pull request merged**
