### PR TITLE
Fix Support Page And Features Page

### PR DESCRIPTION
**Pull request by GGGaming71**

### CODE REVIEW

**Comment by froxcey** [comment]
Thank you for your contribution. 
This page is for support and therefore there could be a small description for what link is for what and how to get support. I would recommend using the features page as inspiration. Also, some of those logos are round and adding a squarish outline looks weird. Either make the logo have square outline (so the whole box has the tint) or remove the outline. That Discord icon is not fully in the box. Good job on making it work on mobile :)

**Comment by froxcey** [comment]
Screenshot 2022-06-17 at 12 49 46 PM
Light theme doesn't work
Logos are too big

**Comment by GGGaming71** [comment]
> Screenshot 2022-06-17 at 12 49 46 PM
> 
> Light theme doesn't work
> 
> Icons are too big
> 
> Please Don't ship WIP

I made icons for light theme but i dont know how to make it so they change once you activate light mode i am trying to figure it out

**Comment by froxcey** [comment]
Hello, this PR seems to have made some progress. I would say this design is not the best, but would do now until designer application closes and we get some new designers. 

Anyways, I found some issues, including the card becoming super small on mobile layout and icons not switching to light mode. Imma start help editing if that's okay

**Comment by GGGaming71** [comment]
> Hello, this PR seems to have made some progress. I would say this design is not the best, but would do now until designer application closes and we get some new designers.
> 
> Anyways, I found some issues, including the card becoming super small on mobile layout and icons not switching to light mode. Imma start help editing if that's okay

yeah thats completely ok and thank you so much for your feedback!

**Comment by GGGaming71** [comment]
> > > Hello, this PR seems to have made some progress. I would say this design is not the best, but would do now until designer application closes and we get some new designers.
> > 
> > 
> > > 
> > 
> > 
> > > Anyways, I found some issues, including the card becoming super small on mobile layout and icons not switching to light mode. Imma start help editing if that's okay
> > 
> > 
> > yeah thats completely ok and thank you so much for your feedback!
> 
> I'm sorry but I cannot do it today. I will do it tomorrow. You can look into other files as example when dealing with light theme, or leave it to me tomorrow.

So should i close this PR or keep it open????

**Comment by AZProductions** [comment]
> > > > Hello, this PR seems to have made some progress. I would say this design is not the best, but would do now until designer application closes and we get some new designers.
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > Anyways, I found some issues, including the card becoming super small on mobile layout and icons not switching to light mode. Imma start help editing if that's okay
> > > 
> > > 
> > > yeah thats completely ok and thank you so much for your feedback!
> > 
> > 
> > I'm sorry but I cannot do it today. I will do it tomorrow. You can look into other files as example when dealing with light theme, or leave it to me tomorrow.
> 
> So should i close this PR or keep it open????

You can keep it open, just ping me when its ready

**Comment by GGGaming71** [comment]
Screen Shot 2022-06-18 at 12 41 45 AM
Screen Shot 2022-06-18 at 12 39 06 AM

Which one do you think is better? (in the second one i tried to put discord's box down with reddit's but i didnt know how to)

**Comment by GGGaming71** [comment]
Are there anymore problems you'd want me to try to fix?

**Comment by froxcey** [comment]
> Are there anymore problems you'd want me to try to fix?

Screenshot 2022-06-18 at 9 13 46 AM

I'm currently working on the spacing of cards. Large screen is fixed, and I'm working on small screens.

**Comment by GGGaming71** [comment]
> > Are there anymore problems you'd want me to try to fix?
> 
> Screenshot 2022-06-18 at 9 13 46 AM
> 
> I'm currently working on the spacing of cards. Large screen is fixed, and I'm working on small screens.
Screen Shot 2
Btw what did you think of this design? is it better or should we just use the current one?
Here it is in a mobile/tablet view
Screen Shot 3

**Comment by froxcey** [comment]
I think the cards are too small on mobile, and I'm working on that. After that, it should be good to go.

**Comment by froxcey** [comment]
All issues I found should be fixed. It's now open for review

**Review by froxcey — APPROVED** [review]
Since people above are offline and no peer is currently on work, I'm just going to review it myself. 

Seems good, merging now.

**Pull request merged**
