### PR TITLE
updated ar_SA.yaml

### PR DESCRIPTION
**Pull request by GGGaming71**

### CODE REVIEW

**Comment by GGGaming71** [comment]
> I think you have updated dependencies on your fork? This is not good as we have not yet tested the newer versions and make sure they don't break anything.

on my fork i don't see any problems from bumping the dependencies tbh but if you say so ig

**Comment by GGGaming71** [comment]
What happened with this pr?

**Review by froxcey — CHANGES_REQUESTED** [review]
All source text should be lowercase. I should probably change this behavior soon... Follow this for now.

**Comment by froxcey** [comment]
Sorry school started so I got pretty busy. I now got a bit of spare time.

**Comment by GGGaming71** [comment]
> All source text should be lowercase. I should probably change this behavior soon... Follow this for now.

I will work on that in a bit

**Comment by GGGaming71** [comment]
@froxcey i made a commit is this what you mean?

**Comment by GGGaming71** [comment]
and also i couldn't really figure out how to resolve the conflicts

**Comment by AZProductions** [comment]
> and also i couldn't really figure out how to resolve the conflicts

You can copy the current package.json and package-lock file and replace them with yours

**Comment by GGGaming71** [comment]
@AZProductions @froxcey what about now? i think its good now

**Review by AZProductions — APPROVED** [review]
LGTM, just waiting for Froxcey to confirm

**Comment by froxcey** [comment]
@AZProductions this PR will update some dependencies. I'm not sure if this will break anything.

**Comment by froxcey** [comment]
Alr I will be reverting all the updates on dependencies, then I'm merging this.

**Comment by froxcey** [comment]
Never mind, I can just test if the updated dependencies will cause any trouble.

**Review by froxcey — APPROVED** [review]
I made some very minor patches, and it should be good to go now. Merging now

vibe

**Comment by froxcey** [comment]
I will also be updating all other languages

**Pull request merged**
