### PR TITLE
Added Spanish translation

### PR DESCRIPTION
**Pull request by FacuA0**
Here i've modified the es_ES locale file to add a Spanish translation to the page, and changed a value in TranslationList so the website can be changed to that language.

### CODE REVIEW

**Comment by FacuA0** [comment]
I forgot to add the tag ;-;

**Review by froxcey — APPROVED** [review]
LGTM! I found a error, but it's not a problem with this PR. I will fix it later myself, merging now.

**Comment by FacuA0** [comment]
Hi. I would like to know what is the error anyways, even if you said that you will fix it later (because supposedly it's my error)

**Comment by froxcey** [comment]
It's a fundamental design flaw in the website, and it will be fixed in #97

**Comment by FacuA0** [comment]
Oh, yes, I see it. Well, glad that it will be fixed soon.

**Pull request merged**
