### PR TITLE
Update downloads.tsx it looks weird

### PR DESCRIPTION
**Pull request by Trynera**

### CODE REVIEW

**Review by Trynera — COMMENTED** [review]
wow looks so much better

**Comment by AZProductions** [comment]
I'm running the ci/cd, but don't have access to my pc.

Could you send screenshot of the result?

**Comment by AZProductions** [comment]
And why did you remove the torrent download button?

**Comment by Trynera** [comment]
> And why did you remove the torrent download button?

so that web doesn't look so empty. it can be added back as a option in a pop up window

**Comment by Trynera** [comment]
> > And why did you remove the torrent download button?
> 
> so that web doesn't look so empty. it can be added back as a option in a pop up window

better

**Comment by AZProductions** [comment]
Sure, it looks great👍

**Review by AZProductions — APPROVED** [review]
LGTM

**Comment by Trynera** [comment]
> LGTM

k

**Comment by froxcey** [comment]
@Trynera 

> it can be added back as an option in a pop up window

If you want to make changes, please make sure it works well. You can make a draft pull request, get feedbacks on what to do. Using this PR as an example, you took away the torrent download button, so maybe you should also add it in the popup.

> LGTM

Tbh it looks very incomplete to me.

**Comment by froxcey** [comment]
This will pass for now. The contribution guideline has been updated to prevent this in the future (justification for this is also in the guide). I will make a PR later to fix this (busy rn).

**Pull request merged**
