### PR TITLE
Refactor translation

### PR DESCRIPTION
**Pull request by froxcey**
Woah, the PR just got merged! Welp, this PR refactor translation related file to component/translation, and locales to components/translation/locale. It will make things easier for translators to work with.

### CODE REVIEW

**Comment by MrSerge01** [comment]
you're a chad, hope this gets merged too, i dont have anything to contribute to now, you have taken every possibility away from me so you're a pro. congrats!!

**Review by AZProductions — APPROVED** [review]
LGTM

**Comment by froxcey** [comment]
> you're a chad, hope this gets merged too, i dont have anything to contribute to now, you have taken every possibility away from me so you're a pro. congrats!!

You can start translating! Start by reading TRANSLATING.md, it has essential info for translating stuff.

**Comment by MrSerge01** [comment]
> > you're a chad, hope this gets merged too, i dont have anything to contribute to now, you have taken every possibility away from me so you're a pro. congrats!!
> 
> You can start translating! Start by reading TRANSLATING.md, it has essential info for translating stuff.

when i will come back home

**Pull request merged**
