### PR TITLE
Unnecessary english variant

### PR DESCRIPTION
**Pull request by akane6704**
I looked through the american english language and it just differs nothing from the traditional english lang, like it's useless

### CODE REVIEW

**Review by akane6704 — COMMENTED** [review]
looking garbage to me

**Comment by akane6704** [comment]
why i can review lol

**Comment by akane6704** [comment]
pls fix this

**Comment by froxcey** [comment]
But en-US got three lines of localisation

**Comment by AZProductions** [comment]
> pls fix this

we cant change that, its part of GitHub's review system

**Comment by akane6704** [comment]
i mean it's changing like three letters

**Comment by akane6704** [comment]
> we cant change that, its part of GitHub's review system

there are organization roles

**Comment by froxcey** [comment]
> i mean it's changing like three letters

Yes, and why not keep it?

**Comment by akane6704** [comment]
okay then, imma close the pr

**Pull request closed without merging**
