### PR TITLE
Add link to demo github in demo.tsx

### PR DESCRIPTION
**Pull request by LucasoDevDotTk**
I can't figure out why TranslationText injection doesn't work, I've added the link to TranslationInjection.tsx, but it still doesn't work. @froxcey please help me.

### CODE REVIEW

**Comment by froxcey** [comment]
I think it might be much easier to just add an optional link/href property to TranslatableText?

**Comment by LucasoDevDotTk** [comment]
ok...

**Comment by LucasoDevDotTk** [comment]
> I think it might be much easier to just add an optional link/href property to TranslatableText? I think I might need to update the library once again.

Yes It would be easier.

**Comment by froxcey** [comment]
#188 when this gets merged, TranslatableText will simply has a link property that you can manipulate.

**Comment by LucasoDevDotTk** [comment]
> #188 when this gets merged, TranslatableText will simply has a link property that you can manipulate.

Ok, I will fix this when I get home.

**Comment by AZProductions** [comment]
@LucasoDevDotTk you can sync your local repo with github for the updated TranslatableText

**Comment by LucasoDevDotTk** [comment]
Thx

**Review by froxcey — APPROVED** [review]
Added translation to files, and LGTM

vibe

**Pull request merged**
