### PR TITLE
Add more appealing content to home page

### PR DESCRIPTION
**Pull request by HeroesOfBalkan**

### CODE REVIEW

**Comment by HeroesOfBalkan** [comment]
As usual, I had problems with creating a PR.

Anyways, I have created a slideshow (somewhat buggy) and some more text, as shown in avdanos channel in official Discord server.

Code needs some more love and optimization.

**Comment by HeroesOfBalkan** [comment]
Note: slideshow isn't optimized and lacks 1-2 features and stylings aren't perfect.

**Review by GGGaming71 — APPROVED** [review]
tbh i think this should be merged for now but i think you should make it so you can also manually scroll through the 5 pages but for now LGTM

**Review by froxcey — APPROVED** [review]
Merging this for now, and we can make some additional changes later.

**Pull request merged**
