### PR TITLE
Translation lib - Styling Update

### PR DESCRIPTION
**Pull request by froxcey**
- The old [%s] tag now has be renamed to [%a] (for hyperlink)
- New [%b] tag for bold
- Moved style injection to StyleInjector.tsx
- New linkStyle property on TranslatableText for CSS styling on injected links

I have migrated all translations to the new system, but please submit a review or PR if you found something wrong.

vibe

### CODE REVIEW

**Review by MrSerge01 — APPROVED** [review]
wow, good work!
you are a literal chad doing magic with the website, im sure you will dominate the window manager development!
LGTM

**Comment by froxcey** [comment]
> im sure you will dominate the window manager development

That won't happen, I suck at Rust

**Comment by MrSerge01** [comment]
> > im sure you will dominate the window manager development
> 
> That won't happen, I suck at Rust

you'll learn it in no time! i believe in you xD

**Review by AZProductions — APPROVED** [review]

**Comment by AZProductions** [comment]
LGTM, thanks!

**Pull request merged**
