### PR TITLE
Translation - Dev Thread

### PR DESCRIPTION
**Pull request by froxcey**
Yes, we are at the point where we can start working on translation. This thread is for web developers only, and translator can start contributing after we decided how translation is going to be done, updated contributing guidelines, and have the project ready. We might also need to open an issue for tracking the progress of translation. 

To do:

- [x] Selection UI
- ~~Automatically default to system locale~~
- [x] Make locale selection persistent
- [x] Make website update according to selected locale (still buggy)
- [x] Make locale template file (almost done)
- [x] Add translator contributing guideline ~~(and select localisation management software)~~'
- [x] Add guide for developer to implement translation

If you want to translate, please read the [translating guideline](https://github.com/Avdan-OS/Website/blob/dev/TRANSLATING.md).

vibe

### CODE REVIEW

**Comment by MrSerge01** [comment]
I can translate to Russian, I don't know how to do so.

**Comment by AZProductions** [comment]
I can help with Dutch

**Comment by froxcey** [comment]
Update: I've got translation somewhat ready (both implementation and storing), but we might need a Crowdin project, however that works. It's not yet fully ready, still very buggy and need a lot of tweaks before production ready, but it's already late in my area and I need to go off now. Any contribution through forking and PR my branch would be appreciated.

**Comment by norwagov** [comment]
I can help with Polish translation

**Pull request merged**
