### PR TITLE
Punctuation and Cap Improvement

### PR DESCRIPTION
**Pull request by Rohith0009**
### Description

To Make The Page More **Attractive** I Have Added Some **Punctuation** And Updated The **Caps** Of The Home Screen!

### CODE REVIEW

**Review by froxcey — CHANGES_REQUESTED** [review]
Please watch out for conventions. FANBOYS words like "and" and"but" are usually not capitalised. Changing of punctuations will mean update in translation files, but you can leave it to me.

**Comment by froxcey** [comment]
Also, please make PR titles concise, and the description is creative yet not really readable. This does not affect anything regarding the actual changes, but following conventions in the contribution guideline does make the review process easier.

**Comment by Rohith0009** [comment]
I Have Updated Fanboy Word To Be In Lowercase And I Have Updated The Description!
Thanks!

**Comment by Rohith0009** [comment]
I have added translation. Please Check

**Review by AZProductions — APPROVED** [review]
LGTM, waiting for a second review

**Review by froxcey — APPROVED** [review]
Looks good, merging now

**Pull request merged**
