### PR TITLE
Goodbye TranslatableText, Hello Translatable

### PR DESCRIPTION
**Pull request by Froxcey**
The old TranslatableText has very limited functionality, so I decided to make a successor to that library. This is simply called "Translatable" cuz it not only works with string but also components. This will be another great library. Wakuwaku!

- [x] Replace TranslatableText with Translatable (P1)
- [x] Basic rewrite of TranslatableText (P1)
- [x] Allow capitalised translation key (P1)
- [x] Decomposition logic (P1)
  - [ ] ~~Use recursive function~~
- [x] Injection logic (P1)
  - [x] Use recursive function (P2)
- [x] Implement layering logic (P3)
- [x] Documentation (P4a)
- [ ] Code clean up
- [ ] Migrate locale files (P4b)

Any help would be appreciated. As you might know, I'm not part of the Discord server anymore, so please contact me through IRC/Matrix `@froxcey:matrix.org` Telegram `@froxcey` or Twitter `@froxcey_`

vibe

### CODE REVIEW

**Comment by Froxcey** [comment]
Btw, give me a better name for this library if you have one. Simply calling it "Translatable" isn't the most interesting.

**Comment by MrSerge01** [comment]
call it chiissu andalso ship a hardcoded japanese translation

**Comment by Froxcey** [comment]
**Quest: チッスレト　Chiissulate**

> ~~Obfuscate~~ Refactor all the variables to Japanese :trollface: 

Difficulty: `medium`
Reward: `10 Troxcoin`

**Comment by Froxcey** [comment]
Progress update: things work too well

Ok, how would a library handle translating this madness
Screenshot 2023-04-01 at 10 36 49 PM
```tsx
<Translatable>
  Your <Link href="https://www.youtube.com/@LinusTechTips">PC</Link> but{' '}
  <button>
    Even <Link href="https://www.youtube.com/watch?v=FtutLA63Cp8">Better</Link>!
  </button>
<Translatable>
```

Idk, I just threw a translation string to this new library to inject using recursive and layer counting
```yaml
Your <%0|PC|%0> but <%0|Even <%1|Better|%1>!|%0>: 您的<%0|個人電腦|%0>，但是<%0|更<%1|好|%1>！|%0>
```
and holy sh!t:
Screenshot 2023-04-01 at 10 39 58 PM

I guess this is part 3 done. Just gotta clean things up, do a final check, write documentation, migrate all the current translations and a bit of DX things in part 4 then it would be ready for review and merge. Need to go make commit now. WAKUWAKU!!! 

vibe

**Comment by MrSerge01** [comment]
good work

**Comment by Froxcey** [comment]
Also, Japanese translation coming soon?! 👀

**Pull request closed without merging**
