### PR TITLE
Chiislate

### PR DESCRIPTION
**Pull request by Froxcey**
(Reopened a new PR due to branch rename)

This PR replaces the old Translatable library with a new shiny Chiislate library. Here are some changes:

- You can now pass React components to translate some madness, for example:

> ```tsx
> <Chiislate>
>   Your <Link href="https://www.youtube.com/@LinusTechTips">PC</Link> but{' '}
>   <button>
>     Even <Link href="https://www.youtube.com/watch?v=FtutLA63Cp8">Better</Link>!
>   </button>
> <Chiislate>
> ```
> 
> Screenshot 2023-04-01 at 10 36 49 PM
> 
> \+
> 
> ```yaml
> Your <%0|PC|%0> but <%0|Even <%1|Better|%1>!|%0>: 您的<%0|個人電腦|%0>，但是<%0|更<%1|好|%1>！|%0>
> ```
> =
> Screenshot 2023-04-01 at 10 39 58 PM
> 

- Translation keys can be capitalised. You can thank me later, fellow translators.
- All the locale files has been migrated and will automatically be compatible with the new library once merged
- Documentations on translating has been updated
- Added a small bit of Japanese translation
- Removed unmaintained translations
- No actual visual change, the website should look exactly identical (except for the new Japanese translation)

vibe

### CODE REVIEW

**Comment by Froxcey** [comment]
@MrSerge01 @Sammy99jsp 

I think this PR is ready. Please do pull and test the code before approving. There's a lot of changes here, and I want this to be bug free before being released.

**Comment by MrSerge01** [comment]
> @MrSerge01 @Sammy99jsp 
> 
> I think this PR is ready. Please do pull and test the code before approving. There's a lot of changes here, and I want this to be bug free before being released.

im on phone...

**Review by TechStudent10 — APPROVED** [review]
If it works then LGTM (I honestly don't know but it looks like you put a lotta effort in)

**Comment by Sammy99jsp** [comment]
Just pulled the PR - seems good to me.

**Review by Sammy99jsp — APPROVED** [review]
LGTM!

**Pull request merged**
