### PR TITLE
Updated sr-SP translation in Cyrillic

### PR DESCRIPTION
**Pull request by HeroesOfBalkan**

### CODE REVIEW

**Comment by HeroesOfBalkan** [comment]
damn, github pr is painful

**Comment by froxcey** [comment]
You ready for this to merge? Also, we cannot do Latin for now because of how the drop down menu works (there's a list of flags, and it's impossible to select Cyrillic or Latin). I will add it when we get the implementation ready.

> damn, github pr is painful

Sorry. We could've went for Crowdin, but we're still sorting it out.

**Comment by HeroesOfBalkan** [comment]
I didn't mean that. I was trying to pull from VSC but VSC doesn't want to collaborate. I am having problems to send a commit, to make a PR, to abort,...

**Review by HeroesOfBalkan — COMMENTED** [review]
I have completed translation to Serbian language in Cyrillic. I haven't tested it yet. I'll try to do it and fix problems

**Pull request closed without merging**
