### PR TITLE
Changed the logo to the new one for darkmode and lightmode

### PR DESCRIPTION
**Pull request by LucasoDevDotTk**

### CODE REVIEW

**Comment by LucasoDevDotTk** [comment]
Working on changing the logo for the android and ios only files.

**Review by froxcey — CHANGES_REQUESTED** [review]
The middle part of the logo should be transparent and not filled with opposite colour.

vibe

**Comment by LucasoDevDotTk** [comment]
Working on that issue rn, should be done in max: 45mins.

**Comment by LucasoDevDotTk** [comment]
thx

**Comment by LucasoDevDotTk** [comment]
Fixed the issue now.

**Review by froxcey — APPROVED** [review]
Looks good, merging now

vibe

**Comment by LucasoDevDotTk** [comment]
Ok

Last ned Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Fra: Froxcey ***@***.***>
Sendt: Friday, July 8, 2022 12:17:18 PM
Til: Avdan-OS/Website ***@***.***>
Kopi: Lucas Nguyen ***@***.***>; Author ***@***.***>
Emne: Re: [Avdan-OS/Website] Changed the logo to the new one for darkmode and lightmode (PR #155)


@froxcey requested changes on this pull request.

The middle part of the logo should be transparent and not filled with opposite colour.

[vibe]<https://user-images.githubusercontent.com/51555391/176177206-ec3f9dce-8780-4fe8-b6ac-5eeeac2038d4.gif>

**Pull request merged**
