### PR TITLE
Fixed - Wrong link to demo

### PR DESCRIPTION
**Pull request by schooldanlp6**

### CODE REVIEW

**Review by SunightMC — APPROVED** [review]
It works so LGTM!

**Review by Froxcey — APPROVED** [review]
> why this demo is linked?

We had three completely different versions of the demo: Facu's, Dynamic's, and Heister's.

When we were putting the link in, which is a crazy long time ago, we decided to put Facu's because it is the most complete version. Heister's later on got more attention than Facu's and had much more work done on. Since the demo team is completely different from the web team, we were not informed of the change, so the link still leads to Facu's demo and not Heister's. 

LGTM 👍 

vibe

**Comment by Froxcey** [comment]
Btw I don't have merge perm, so someone need to push that button for me.

**Comment by Sammy99jsp** [comment]
I'll merge then.
Weird you don't have perms.

**Comment by Sammy99jsp** [comment]
@Froxcey I have invited you to be a maintainer for this repo — hope that works.

**Comment by SunightMC** [comment]
> I'll merge then. Weird you don't have perms.

I think it's because Froxcey is no longer in the GitHub organisation 😅

**Pull request merged**
